### ISSUE TITLE
Adding a new contact doesn't automatically populate the phone number from the dialer

### ISSUE THREAD

**Issue by user8446** [you-apps/ConnectYou#129]
### Steps to reproduce

Hi,

This is a re-open of https://github.com/Bnyro/ConnectYou/issues/127

The number now populates as expected if adding a new contact from the messages app and visual voicemail app, but the phone number still does not populate when adding a new contact from the dialer app.

### Expected behavior

Phone number populates from the dialer app when adding a new contact

### Actual behavior

Phone number does not populate from the dialer app when adding a new contact

### Connect You version

3.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You mean when you choose the "Create new contact" instead of the "Add to contact" option in your dialer? Then I probably misunderstood your previous issue which had an issue with that too :)

**Comment by user8446** [comment]
Meaning the creating a contact from the messages app works perfectly. After clicking "Add contact" in messages, it jumps to the ConnectYou "Add to contact" screen where you can add to an existing contact or create a new one.  When creating a new one, the phone number automatically populates.

The issue is after clicking "Add contact" from the dialer app, it should follow the steps like above. Instead, it open into the page where you are creating a new contact and the phone number isn't populated:


![Screenshot_20230405-190438 (3)](https://user-images.githubusercontent.com/18019245/230232721-4c37d777-674a-478d-8871-f07033361296.jpg)

Actual behavior:

![Screenshot_20230405-190523](https://user-images.githubusercontent.com/18019245/230232786-1bafc500-b35f-43a1-a073-611d536c260d.jpg)


Expected behavior:

![Screenshot_20230405-191230](https://user-images.githubusercontent.com/18019245/230232811-33df748c-c0a7-4c99-87f0-b0b0043a7b10.jpg)

**Comment by Bnyro** [comment]
Please feel free to test the latest debug build as I'm not exactly sure if it works as intended now since none of the apps I use provides the ability to create new contacts by already sharing some information!

**Comment by pabloscloud** [comment]
I'll try it

**Comment by user8446** [comment]
I'll be glad to test. Can you point me to this test debug build please?

**Comment by Bnyro** [comment]
Sure, https://github.com/Bnyro/ConnectYou/actions/runs/4660947267

**Comment by user8446** [comment]
Thanks, I tested and from the dialer app it does now populate the phone number as expected but it still opens into the new contact page instead of the "Add to contact" page where you can selectively add the number to an existing contact or add a new one.

It still works correctly from the messages app.

FYI I'm on the stock google phone dialer app.

**Comment by Bnyro** [comment]
Yes, that's the intended behavior. The `insert contact` action, that can be called by other apps, is meant to create a new contact, while the `add to contact` action (callable by other apps too) allows the user to choose.

**Comment by user8446** [comment]
Hi,

Both the messages app and dialer app just have a single "Add contact", without an option to choose. The user should then be able in ConnectYou to either add the number to an existing contact or create a new one.

This is the flow from messages and works correctly.

From the dialer app, ConnectYou doesn't give the option the either add to an existing contact or create a new one. It goes directly to the create a new contact screen and you are unable to add the number to an existing.

I can attach screenshots if it helps.

**Comment by Bnyro** [comment]
I know what you're referring to however, Connect You follows the official guidelines from https://developer.android.com/guide/components/intents-common#InsertContact which do not foresee to allow users the choice when the action equals `Intent.ACTION_INSERT`. The "Add to contact" functionality is available when you start typing a number in the Google dialer and then click "Add to contact".

**Comment by user8446** [comment]
Ok I tried the official google contacts app to see how it handled it.  There is an "add to existing" button that allows users to add to an existing contact but your app would stay in the guidelines:

---

Click add contact from the dialer app:

![Screenshot_20230411-165145 (2)](https://user-images.githubusercontent.com/18019245/231293905-f6d625d5-15ae-408e-9d3d-e379c8a333c0.jpg)

---

In Google contacts, there is an add to existing button:


![Screenshot_20230411-164907 (2)](https://user-images.githubusercontent.com/18019245/231294185-7c87fbda-e6bd-4ecf-8d0a-85dfd24c9890.jpg)

**Comment by user8446** [comment]
@Bnyro Hi just a friendly ping to see if got the above.

The only scenario left is adding to an existing contact from the dialer. An "Add to existing" button would solve unless you prefer a different way?
