### ISSUE TITLE
Icon following theme

### ISSUE THREAD

**Issue by tadekdudek** [you-apps/ConnectYou#149]
### Describe your suggested feature

The app icon looks bad when using light theme. It should follow the theme.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the suggestion, however I don't want the icon to look different per theme.
