### ISSUE TITLE
Automatic backups options don't fit on screen

### ISSUE THREAD

**Issue by Cameo007** [you-apps/ConnectYou#219]
### Steps to reproduce

1. Open the app
2. Go to settings

### Expected behavior

It should not be aligned vertically.

### Actual behavior

The last option for automatic backups (Both) is aligned vertically because there is no space. And in english there is no text.

### Connect You version

6.0

### Android version

Android 13

### Other details

![Screenshot_20230816_230057_Connect You](https://github.com/you-apps/ConnectYou/assets/80521473/1e51fc5c-48d2-48cb-a948-3f0a12c038e4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
I've seen this too, after installing the app on someone's phone. It doesn't show up on my phone though. I think I know how to fix it, but won't be able to test it afterwards...
Jetpack Compose doesn't officially support segmented buttons yet. When it does we'll switch to them. That will prevent issues like this and save us some lines.
