### ISSUE TITLE
Filter: use app names instead of package names

### ISSUE THREAD

**Issue by Cameo007** [you-apps/ConnectYou#220]
### Describe your suggested feature

It would be nice if the app would use app names (WhatsApp, Signal, Davx5) instead of their package names (com.whatsapp, etc.) for the filter options.
One point is, that package names are long, so you have to scroll longer. Another point is, that some people might not know, that `org.thoughtcrime.securesms` is Signal.

### Other details

![Screenshot_20230816_231221_Connect You](https://github.com/you-apps/ConnectYou/assets/80521473/b4f36f01-5253-4644-bacd-b5eb3168dddd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Maybe we should display both? Certainly, two apps can have the same name, so that only their app id can identify them.
