### ISSUE TITLE
Add option to sort by last name but show first name first

### ISSUE THREAD

**Issue by Zumux** [you-apps/ConnectYou#225]
### Describe your suggested feature

So that a name will show as 'John Smith' instead of 'Smith, John' when sorted by last name

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't consider this useful, sorry.
