### ISSUE TITLE
Display scrollbar with letters

### ISSUE THREAD

**Issue by FineFindus** [you-apps/ConnectYou#227]
### Describe your suggested feature

Use a scrollbar with letters, allowing the user to quickly jump/scroll to the specific letter. See example of [Koler](https://github.com/Chooloo/koler) below.

### Other details

![Koler](https://github.com/you-apps/ConnectYou/assets/63370021/8eb87259-99ed-4358-87a4-d6103cca9525)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
A scrollable alphabet like the one Niagara Launcher uses would be quite amazing actually. Niagara is not open source unfortunately.

![unnamed](https://github.com/you-apps/ConnectYou/assets/82398591/4fa89526-1eb4-4871-afb6-0d4be5db51af)

**Comment by Bnyro** [comment]
Jetpack Compose does not yet support scrollbars natively - so we would have to build one from scratch. Unfortunately, I don't think an alphabetical scrollbar like in the screenshot would really look good inside the app currently.

**Comment by M00NJ** [comment]
In that case I'd say we wait. I think this is a very useful feature because it improves intuitiveness, but it can wait. It seems quite a few things are missing in compose (Searchbars, Segmented buttons, etc.)

**Comment by SuhasDissa** [comment]
#297
