### ISSUE TITLE
Automatic backup not working

### ISSUE THREAD

**Issue by Vinfall** [you-apps/ConnectYou#229]
### Steps to reproduce

Auto backup:
1. Go to settings
2. Enable `encrypt backups as zip` option
3. Choose `local` in automatic backup
4. Choose and select a folder when prompted (its path is `sdcard:/Aaa/backup`)
5. Wait for many times the interval time (2h) and there is still no backup in the target folder

### Expected behavior

There should be backups in the target folder.

### Actual behavior

There is no backup in the target folder.

### Connect You version

6.0 (23)

### Android version

Android 12 (originOS, iQOO)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Disable all battery restrictions for the app - otherwise it won't work.

**Comment by Bnyro** [comment]
I'm using this frequently, so it's not a general issue of the app.

**Comment by Vinfall** [comment]
Fair enough, I'll try that.

**Comment by Bnyro** [comment]
Automatic backup did not work due to an issue with the preferences, which didn't get saved properly - will be fixed with the next release.
