### ISSUE TITLE
Contact got stored in nowhere

### ISSUE THREAD

**Issue by SuhasDissa** [you-apps/ConnectYou#231]
### Steps to reproduce

1. Open the app
2. Move one or more contacts from 'Device' to 'Local'
3. Then move them back to 'Device'

### Expected behavior

The contact should be moved to 'phone' section of the stock contacts app.

### Actual behavior

The contact is actually created in the phone's storage. and the ConnectYou app shows it properly.

<img src="https://github.com/you-apps/ConnectYou/assets/64766434/5907b208-ebbd-42b4-a9cb-fd59f041a34b" width="30%">

However, in the stock android contacts app, the contact is not visible under the 'phone' section.

### Connect You version

6.0

### Android version

Android 12

### Other details

All my contacts are stored in my google account. So in above step two, the contact got moved from google account to local.

After moving the contact back and forth the contact is now not inside the google account or the phone storage.
But the contact is still there when I navigate to the "All contacts" section of the stock contacts app. (See screenshots)

<img src="https://github.com/you-apps/ConnectYou/assets/64766434/918ac465-095e-4765-94c7-9b07e347706e" width="30%">

Apart from all those issues, now I can't figure out a way to move the contact back to my google account. Apparently, the contact is not stored in the phone or the sim card.

<img src="https://github.com/you-apps/ConnectYou/assets/64766434/6553a36e-f47d-41d1-8051-e6008a289fa3" width="30%">

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't have any phone with Google services to test this on, I suspect we're using a different account type and account name than the Google contacts app. Can you try to debug what `accountType` and `accountName` are for contacts created by Google contacts? For reference: https://github.com/you-apps/ConnectYou/blob/main/app/src/main/java/com/bnyro/contacts/util/DeviceContactsHelper.kt#L96

**Comment by SuhasDissa** [comment]
BTW I'm using the stock Samsung contacts app.

I looked at the contact storage location. ConnectYou contact storage location is shown as `Phone (DEVICE)`
And Samsung contacts app created contact storage location is shown as `Phone Storage`

| Created by Contact You | Created by Samsung contacts |
| --- | --- |
| <img src="https://github.com/you-apps/ConnectYou/assets/64766434/5a2aafbb-b9ec-49c6-90cd-4cca2e2b056f"> | <img src="https://github.com/you-apps/ConnectYou/assets/64766434/425b0be6-ee75-4be3-84f5-b132632c0768" > |

**Comment by Bnyro** [comment]
What are they using as `accountType` then?

**Comment by Bnyro** [comment]
The stock android contacts app uses `com.android.contacts`, and so does Connect You.

**Comment by SuhasDissa** [comment]
In ConnectYou filter dialog there are 4 accounts.
ConnectYou : `DEVICE`
GoogleAccount : `{My gmail address}`
Sim card (I assume) : `5190424673`
SamsungContacts : `vnd.sec.contact.phone`

**Comment by Bnyro** [comment]
Interesting!
If you set the type to your google account for example when creating a new contact in Connect You via the UI, does Google display it then? (Or the same with Samsung).
Maybe we should allow users to also choose an account type when importing vcards and moving contacts from local to device.

**Comment by Bnyro** [comment]
> Maybe we should allow users to also choose an account type when importing vcards and moving contacts from local to device.
>
So this should probably resolve the issue I assume?

**Comment by SuhasDissa** [comment]
BTW that random number thing is not the sim card. Those are the telegram contacts.

**Comment by SuhasDissa** [comment]
> > Maybe we should allow users to also choose an account type when importing vcards and moving contacts from local to device.

I think most people would find the account name `vnd.sec.contact.phone` to be a bit too technical. I doubt anyone would actually choose it

**Comment by Bnyro** [comment]
Well, but that's probably to only way to resolve that issue?

**Comment by SuhasDissa** [comment]
https://stackoverflow.com/questions/45768948/how-can-i-get-the-default-phone-and-sim-contacts-account-type-and-account-name
