### ISSUE TITLE
Support for Welefon API

### ISSUE THREAD

**Issue by N1N74** [you-apps/ConnectYou#239]
### Describe your suggested feature

Local contacts can be used with a dialer app that uses API to fetch caller info such as [Welefon](https://codeberg.org/wivewa/wivewa-dialer-android).

When receiving calls from contacts in local storage, the dialer will now be able to display caller information through the API.

Potential alternatives to #124 #170

### Other details

[Simple dialer](https://f-droid.org/en/packages/com.simplemobiletools.dialer/) also has this feature working with its own contacts app but I am unsure how that works.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Welefon doesn't seem very popular and we don't aim to support or promote any apps other than ours more than others.

We follow the documented Android standards, which is supported by every common dialer app.
