### ISSUE TITLE
Expand search capabilities

### ISSUE THREAD

**Issue by N1N74** [you-apps/ConnectYou#241]
### Describe your suggested feature

Expand the search functionality to more fields like notes and email. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Crazy-Unicooorn** [comment]
Came to say this! Would be awesome to get search results based on notes also, à must have improvement for me.

Keep up the great work.
