### ISSUE TITLE
Share contacts as qr code

### ISSUE THREAD

**Issue by N1N74** [you-apps/ConnectYou#243]
### Describe your suggested feature

Option to display a qr code of the contacts on selecting "share" in the selecting fields dialog menu (share dialog menu). 

This dialog menu could present options: save as vcf, share as vcf, send to local/device or 'move', display as QR code.

### Other details

*sending to local or device gives more control of which fields are kept during moving.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by N1N74** [comment]
Barcode scanner can already take the vcf shared and generate a QR code, so I would not consider having this feature built-in as high priority.

**Comment by Bnyro** [comment]
I use Barcode scanner as well and thus don't aim to add support for it here.
