### ISSUE TITLE
Selecting the SIM card from which contacts will be imported

### ISSUE THREAD

**Issue by Artem13327** [you-apps/ConnectYou#260]
### Describe your suggested feature

Some may have 2 SIM cards

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Lifehack: remove the Sim card you don't want to use, import contacts from Sim, done.
Not needed imo.
