### ISSUE TITLE
Crash when opening Messages view

### ISSUE THREAD

**Issue by teemue** [you-apps/ConnectYou#270]
### Steps to reproduce

1. Click Messages on the bottom bar

### Expected behavior

Show Messages view

### Actual behavior

The app crashes instantly

### Connect You version

7.0

### Android version

Android 11

### Other details

I uninstalled previous Connect You installation and checked that all permissions are given for the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please get a crash log via adb and share it here.

**Comment by teemue** [comment]
It gives this error:

`09-20 16:12:48.445  7313  7313 E AndroidRuntime: FATAL EXCEPTION: main
09-20 16:12:48.445  7313  7313 E AndroidRuntime: Process: com.bnyro.contacts.debug, PID: 7313
09-20 16:12:48.445  7313  7313 E AndroidRuntime: java.util.NoSuchElementException: Array is empty.
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at kotlin.collections.ArraysKt___ArraysKt.first(_Arrays.kt:1012)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at com.bnyro.contacts.util.PermissionHelper.checkPermissions(PermissionHelper.kt:10)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at com.bnyro.contacts.ui.screens.SmsListScreenKt$SmsListScreen$1.invokeSuspend(SmsListScreen.kt:73)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.k
t:81)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.an
droid.kt:41)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.
kt:68)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1350)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:1040)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:233)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8063)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
09-20 16:12:48.445  7313  7313 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)`

And to mention: i have to give access to messages manually (both release and debug version), the app does not ask for it.

**Comment by Bnyro** [comment]
Thanks for the logs, I'll create a release with the fix later today!

**Comment by teemue** [comment]
> Thanks for the logs, I'll create a release with the fix later today!

Thank you, the latest release works.
