### ISSUE TITLE
Connect You seems to be DELETING ALL CONTACTS

### ISSUE THREAD

**Issue by julianfairfax** [you-apps/ConnectYou#275]
### Steps to reproduce

1. Import contacts from somewhere (say, Proton Mail)
2. Wait like a day or two
3. All contacts lose everything but their phone numbers (and in some cases seem to lose most of them as well)
4. Phone numbers aren't picked up by apps either
-> Contacts are broken

### Expected behavior

This should not happen

### Actual behavior

This seems to happen

### Connect You version

6.3 (23)

### Android version

13 (GrapheneOS)

### Other details

I have the stock Contacts app disabled, and the only apps accessing my contacts are: Connect You itself, K-9 Mail, the stock Messaging app, the stock Phone app, Proton Mail, and Signal. None of those should alter my contacts without any interaction, so the only conclusion I can come to is that Connect You is mishandling them in some way, that breaks them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
I cannot reproduce this. One oft my contact has lost it's phone number a while ago, but I think that came from archiving it and unarchiving it.

**Comment by julianfairfax** [comment]
It takes me like a day or two of doing nothing special for it to happen. I'm not sure what the conditions for reproducing are. It just occurs.

**Comment by julianfairfax** [comment]
We'll see if this occurs on 7.1

**Comment by julianfairfax** [comment]
Update: this issue still happens on 7.1, and it is not actually that the contacts are broken. Rather, they are all entirely deleted. The contacts I'm left seeing, with only phone numbers, are from Signal.

Luckily, I have my contacts stored on Proton Mail as well. For those who don't have backups of their contacts, an occurrence of this issue would be nothing short of catastrophic.

**Comment by Bnyro** [comment]
I'm using the app since more than half a year now and my contacts are still there, I doubt Connect You is the issue here.

**Comment by Bnyro** [comment]
We don't support the GrapheneOS contact spaces or whatever they are called, if you use that then on your own risk.

**Comment by julianfairfax** [comment]
> I'm using the app since more than half a year now and my contacts are still there, I doubt Connect You is the issue here.

I have never ever had this issue before, and now I have had it multiple times. Each time, I was using Connect You.

> We don't support the GrapheneOS contact spaces or whatever they are called, if you use that then on your own risk.

I don't use those.

**Comment by M00NJ** [comment]
Im on GrapheneOS as well and have never experienced this issue.

**Comment by M00NJ** [comment]
Plesse switch between "Device" and "Local" at the top left and see if that changes something.

**Comment by julianfairfax** [comment]
What do you mean by switching between? Simply as the view? I know the contacts are deleted, since other apps also fail to detect them. Or do you mean adding my contacts to local instead of device? Presumably, local contacts are only available in Connect You, which I don't want.

**Comment by julianfairfax** [comment]
It appears this happens when another app is granted access to the contacts.

**Comment by M00NJ** [comment]
I still don't think ConnectYou is causing it. Nobody else ever reported anything like this. Let's try to find out:

Please copy your contacts to your phone again and disable all other contacts apps besides ConnectYou for the time periond you said it occurs in. If it happens again, copy the contacts to your phone again, enable the other apps and disable ConnectYou for the same time period. Report the results here.

**Comment by M00NJ** [comment]
Did you test it?

**Comment by julianfairfax** [comment]
No. If this is not repro I will not keep it open. If someone else has it, they can find this issue again. I have no reliable way to reproduce the issue myself, so there's no real testing to be done.

**Comment by M00NJ** [comment]
Sounds like Threema is the problem here.

**Comment by Vijorich** [comment]
> Sounds like Threema is the problem here.

I have this problem too, and I don't have Theerma installed
Don't know why, but connect you just wipe all contacts ~every week

**Comment by Vijorich** [comment]
> I still don't think ConnectYou is causing it. Nobody else ever reported anything like this. Let's try to find out:
> 
> Please copy your contacts to your phone again and disable all other contacts apps besides ConnectYou for the time periond you said it occurs in. If it happens again, copy the contacts to your phone again, enable the other apps and disable ConnectYou for the same time period. Report the results here.

And yeah it happens only with connect you, I've tried another contact apps with connect you deleted
It happens only with connect you
