### ISSUE TITLE
Select which SIM to send a message from

### ISSUE THREAD

**Issue by julianfairfax** [you-apps/ConnectYou#277]
### Describe your suggested feature

Phones with multiple SIM cards should have option to set which SIM you would like to message from, when using Connect You's built-in messaging feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't this just be selected in the Android settings system wide? I doubt we should mix in to that.

**Comment by julianfairfax** [comment]
> Can't this just be selected in the Android settings system wide? I doubt we should mix in to that.

It can be. But that doesn't work when you have different SIMs for different purposes. Additionally, Android has an Ask every time option, which I have no idea how Connect You would handle.

**Comment by julianfairfax** [comment]
> But that doesn't work when you have different SIMs for different purposes. 

For this reason, it must be possible to select the SIM for each message sent (and to use the previously used one, the default Android one if none is specified and it's the beginning of the convo, or ask if the default Android one is set to ask every time and it's the beginning of the convo - or alternatively, have a per-convo setting instead).

Otherwise, users wanting to use both SIMs like this would have to go to the Android settings, switch the SIM, send a message, switch it back, etc. - an impossible task.

**Comment by Bnyro** [comment]
I don't have a 2nd Sim and hence wouldn't be able to test it, thus I don't plan to add it myself. If someone has two SIM cards and is willing to create a PR, feel free to do so.
