### ISSUE TITLE
Add ripple effect and haptic feedback

### ISSUE THREAD

**Issue by NeuroException** [you-apps/ConnectYou#281]
### Describe your suggested feature

A ripple effect on all controls (especially the contact item) would make the app feel more responsive.

The same goes for haptic feedback. Haptic feedback could be used for when you hold on a contact to select it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We already have ripple effects for most actions, also on contacts items.

Haptic feedback is not really planned.
