### ISSUE TITLE
Side menu instead of dropdown menu

### ISSUE THREAD

**Issue by NeuroException** [you-apps/ConnectYou#282]
### Describe your suggested feature

A side menu would not only look more modern, but also hold more place for future features that may come. The dropdown menu currently implemented looks kinda out of place.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I personally like the current solution for its minimalism, hence I'd prefer not doing any changes here.

Before implementing it, @M00NJ , @SuhasDissa and me already discussed what the best solution for that would be.

Options @M00NJ and @SuhasDissa ?

**Comment by M00NJ** [comment]
Correct me if I'm wrong: I think NeuroExeption means a navigation drawer https://m3.material.io/components/navigation-drawer/overview with "side menu", so I'm against it since this component is used to navigate between destinations not select options.

**Comment by NeuroException** [comment]
> Correct me if I'm wrong: I think NeuroExeption means a navigation drawer https://m3.material.io/components/navigation-drawer/overview with "side menu", so I'm against it since this component is used to navigate between destinations not select options.

Ah, my bad. Yes, i meant the navigation drawer. I was in the thinking that it could be used for more than just navigation.
