### ISSUE TITLE
Selective share specific items of type. 

### ISSUE THREAD

**Issue by kevincox** [you-apps/ConnectYou#285]
### Describe your suggested feature

When doing a selective share it would be nice to select specific instances of a type such as "phone number" or "email". Right now if you select "email" it shares all emails. Often times I have various emails for a contact that I want to preserve but I only want to share their primary email with others. 

### Other details

Related to https://github.com/you-apps/ConnectYou/issues/175

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned due to the necessary complexity needed while it's only an edge case feature.
