### ISSUE TITLE
contact list is not in alphabetical order

### ISSUE THREAD

**Issue by fallsdevil** [you-apps/ConnectYou#287]
### Steps to reproduce

By opening **Connect You**, my contacts aren't in alphabetical order and I couldn't find any options on this in the settings.

### Expected behavior

Was there any option or something that we could configure in which way we want the order of the contacts to appear, in addition to the alphabetical order it could be something like frequent contacts, or favorites, etc.

### Actual behavior

However, I don't know if this is really a "bug" or just some instability in my device, but I think the suggestion of contact list types would be great. I will leave a screenshot showing the order reversed.
![Screenshot_20231001_220710](https://github.com/you-apps/ConnectYou/assets/142761950/7c6ac510-24d1-4808-bceb-41384782cd38)

### Connect You version

7.1 (25)

### Android version

Android 12 (Go Editon)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can change the sortorder in the filter menu at the top right. I don't see any issue in the order in your screenshot however.
