### ISSUE TITLE
Implement fast scrolling (Must)

### ISSUE THREAD

**Issue by KSinghofficial** [you-apps/ConnectYou#289]
### Describe your suggested feature

I have to scroll very hard through my fingers to go through entire contacts / messages lists.
That's because you have not implemented fast scrolling in lists.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Jetpack Compose does not support that.
