### ISSUE TITLE
SMS-Page UI Changes

### ISSUE THREAD

**Issue by NeuroException** [you-apps/ConnectYou#292]
### Describe your suggested feature

A few suggestions for the sms page.

- Primary accent color for messages from yourself (More contrast)
- A rounded textbox with a lighter background, like seen in the second screenshot (Gives more contrast too)
- Overall more rounded up corners for the message bubbles.
- Put Send-button in a circular shape with accent color as background, like seen in the second screenshot (but with same height as textbox).

![PSX_20231006_195354](https://github.com/you-apps/ConnectYou/assets/118199015/4b02df8d-8c74-42e0-aae8-2d835e7eac7a)
![PSX_20231006_200145](https://github.com/you-apps/ConnectYou/assets/118199015/79c28af2-e4bb-4f1c-b09b-ea8df388a034)

### Other details

Overall, the You-Apps-Suite is making great progress. These apps have a better material you implementation than googles apps themself. Great work!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
#297
