### ISSUE TITLE
UI-Improvements in Messages-Section

### ISSUE THREAD

**Issue by NeuroException** [you-apps/ConnectYou#293]
### Describe your suggested feature

- Decrease the size of the chat-items and their profile pictures to match the look of the contact-items.
Currently, the chat-items are bigger, and their profile pictures are unproportionally huge. 

- The border radius does not match either.
- The "Me" contact has a profile picture, which is not visible in the messages-section.

Chat-items:
![PSX_20231006_201013](https://github.com/you-apps/ConnectYou/assets/118199015/46f92447-c3ef-45d4-9251-de04b91ec899)
Contact-items:
![PSX_20231006_201325](https://github.com/you-apps/ConnectYou/assets/118199015/c718e95e-2b02-4383-936b-0637c414a7ee)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
#297
