### ISSUE TITLE
Predictive Back-Gesture

### ISSUE THREAD

**Issue by NeuroException** [you-apps/ConnectYou#295]
### Describe your suggested feature

Implement support for the predictive back gesture on android 14.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned from our POV as Compose doesn't yet properly support it, feel free to create a PR if you find useful resources and get a working implementation running.
