### ISSUE TITLE
Faulty GitHub binary

### ISSUE THREAD

**Issue by KSinghPro** [you-apps/ConnectYou#303]
### Steps to reproduce

I installed connect you from GitHub binary
https://github.com/you-apps/connectyou/releases
When clicking on messages tab app crashes 
I tried again and again and cleared app data and catch.
But that didn't worked then
I installed it from F-Droid it worked perfectly as expected.
So it must be a fault in GitHub binary.

### Expected behavior

When installing app from GitHub binary app should work as expected.
(It works perfectly when app gets installed from F-Droid)

### Actual behavior

It crashes on clicking on messages tab

### Connect You version

Latest

### Android version

Oreo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KSinghPro** [comment]
I again uninstalled app , then installed from GitHub binary it crashed on clicking on messages tab ,
While installing app from F-Droid it works perfect.
It is reproducible and the problem is in GitHub binary https://github.com/you-apps/connectyou/releases Here.

**Comment by kenderipa** [comment]
I have the same behaviour for my Realme Tab mini, Android 11. However, on my Galaxy 23, Android 13 both binaries work fine.

**Comment by KSinghPro** [comment]
> I have the same behaviour on my Realme Tab mini, Android 11. However, on my Galaxy 23, Android 13 both binaries work fine.

Try installing it from F-Droid and report back.

**Comment by kenderipa** [comment]
> > I have the same behaviour on my Realme Tab mini, Android 11. However, on my Galaxy 23, Android 13 both binaries work fine.
> 
> Try installing it from F-Droid and report back.

I just did, above :) F-Droid binary works on both devices, Github binary works only on my Samsung smartphone.

**Comment by KSinghPro** [comment]
@Bnyro See the fault is in GitHub binary as you can see from both two different situations
(With different devices).

**Comment by SuhasDissa** [comment]
![image](https://github.com/you-apps/ConnectYou/assets/64766434/69746519-d10a-46c7-a797-e4efdb87bb02)

Both files are the same

**Comment by kenderipa** [comment]
Now I get it. I'm using Obtainium, and it sees version 7.0 as the last one, not 7.1, since the latter isn't listed among releases, but among tags. And the version 7.0 suffers from the aforementioned bug.
