### ISSUE TITLE
HistoryCallLog Tab [feature]

### ISSUE THREAD

**Issue by DI555** [you-apps/ConnectYou#307]
### Describe your suggested feature

Great, if to be implemented and another useful tab in the app - it’s History Call Log!
Many thanks in advance!

### Other details

Just for calling much easily to pick another useful tab in CY!..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm not sure how useful this would be as you're not able to call people with Connect You directly.

**Comment by M00NJ** [comment]
> why not? ..the goal is to be possible and calling directly either!

It would be nice to have a dialing feature in ConnectYou, but as of now it's neither planned nor being worked on afaik, so I will close this as 'not planned' for now. If we add the dialing feature, we'll naturally add call history as well, but without it a history tab doesn't make much sense.
