### ISSUE TITLE
App request: Interval You

### ISSUE THREAD

**Issue by Toiletmason** [you-apps/ConnectYou#309]
### Describe your suggested feature

I've been looking for an open source replacement for Interval timer for years. There isnt anything comparable, and it seems like a fairly simple app. https://play.google.com/store/apps/details?id=cc.dreamspark.intervaltimer

### Other details

I know this is probably the wrong place to request this, but this is where your website took me, and I don't have a Matrix account.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We don't accept app suggestions.
We already have an app with a timer feature, Clock You, though.
