### ISSUE TITLE
Support receive contact via SMS

### ISSUE THREAD

**Issue by xmha97** [you-apps/ConnectYou#310]
### Describe your suggested feature

Please support send contact via SMS

![Screenshot_2023-11-04-01-33-24-444_com bnyro contacts](https://github.com/you-apps/ConnectYou/assets/23485114/5e0678fc-74de-43d3-9357-d6ca2b64bacc)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
As there is no SMS standard for this unfortunately and we only want to support very basic messaging, this is out of scope.
