### ISSUE TITLE
Black background for dark theme

### ISSUE THREAD

**Issue by GuiSousa135** [you-apps/ConnectYou#316]
### Describe your suggested feature

Whether by default or with an on/off option, I think it's important to have a black background in dark mode throughout the app.

### Other details

When activated, include the black background also in message chats and in the contacts view/edit tab.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
The background color is part of the Material You theme, as you can tell by the slight tint based on the chosen accent color. We will not deviate from the color system and hardcode a value for the backgroundcolor. If you want to request an oled theme you can do this at: #297
