### ISSUE TITLE
Doesn't import birthdays from Proton

### ISSUE THREAD

**Issue by julianfairfax** [you-apps/ConnectYou#318]
### Steps to reproduce

1. Export a contact containing a birthday from Proton Contacts
2. Import it into Connect You

### Expected behavior

Everything should be imported, including the birthday

### Actual behavior

Everything (that I have in the contacts I have tested) is imported, except the birthday

### Connect You version

8.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Example vcf file?

**Comment by julianfairfax** [comment]
[Test -2023-11-18.txt](https://github.com/you-apps/ConnectYou/files/13401013/Test.-2023-11-18.txt) (due to GitHub's file upload restrictions, you will have to rename the file to .vcf)
