### ISSUE TITLE
Feature request: archiving chats

### ISSUE THREAD

**Issue by julianfairfax** [you-apps/ConnectYou#324]
### Describe your suggested feature

It would be nice if you could archive a chat, so you can keep the SMS messages from it, but have a clean chats list.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope for the project.
