### ISSUE TITLE
Save events/birthdays dates without the year

### ISSUE THREAD

**Issue by GuiSousa135** [you-apps/ConnectYou#325]
### Describe your suggested feature

Option to edit and save contacts with events/birthdays dates  without having to add the year, just MM/DD, for example.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
According to the vcard RFC, dates must contain a year.

See https://www.rfc-editor.org/rfc/rfc6350.html#section-6.2.6.
