### ISSUE TITLE
Feature request: copy message text

### ISSUE THREAD

**Issue by julianfairfax** [you-apps/ConnectYou#326]
### Describe your suggested feature

It would be nice if you could copy the text from a message you sent or were sent.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can already select the message text for copying by long pressing it.
