### ISSUE TITLE
Feature request: sending media

### ISSUE THREAD

**Issue by julianfairfax** [you-apps/ConnectYou#329]
### Describe your suggested feature

It would be nice if you could send media as messages (photos, videos, files, etc.).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope for the project, the SMS feature is only meant to be used for receiving TANs mostly.
