### ISSUE TITLE
No support for MMS

### ISSUE THREAD

**Issue by ViktorKahu** [you-apps/ConnectYou#330]
### Steps to reproduce

1. When an mms is sent to your number, no notification or anything received.
2. No option to send image/mms from your phone.

### Expected behavior

Because of the need to set this app as the device's default sms app to use the message features, all the features of standart SMS apps need to be available (otherwise this is a waste of time), hence why I raised this as a bug and not a feature request.

### Actual behavior

MMS not supported.

### Connect You version

8.1

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned to be added. If you rely on MMS, please don't set Connect You as your default messenger app.
