### ISSUE TITLE
Send longer messages

### ISSUE THREAD

**Issue by julianfairfax** [you-apps/ConnectYou#337]
### Describe your suggested feature

It would be nice if the app could be used to send longer messages.

### Other details

Currently, when you send a message, it sometimes says it's too long, which means you have to send multiple shorter ones.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You mean we should automatically split them into multiple messages?

**Comment by Bnyro** [comment]
We can't send messages with more than 160 chars, that's just how SMS works.

**Comment by julianfairfax** [comment]
> You mean we should automatically split them into multiple messages?

That or send them as MMS, yes. The stock Android messaging app probably splits them, but it just shows it all as one in the UI from the perspective of the sender.

**Comment by Bnyro** [comment]
As already said, we won't support MMS.
