### ISSUE TITLE
Ability to hide SMS view

### ISSUE THREAD

**Issue by eennoo** [you-apps/ConnectYou#343]
### Describe your suggested feature

As a user I am using the app to manage contacts. I do have another app for SMS (one that supports RCS). If I don't have the app as my default SMS app, there should be an option to hide the bar in the bottom of the app as I'd only have the Contacts view enabled.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Just don't use it if you don't need it.

**Comment by eennoo** [comment]
Gotcha. Just a suggestion. Thanks for the quick response. :)
