### ISSUE TITLE
After importing a contact file, the whole filepath is displayed on top (overflowing)

### ISSUE THREAD

**Issue by foxyseta** [you-apps/ConnectYou#351]
### Steps to reproduce

Open a vcd file

### Expected behavior

The chat title shouldn't overflow

### Actual behavior

The whole filepath of the vcf file seems to be displayed as the chat title. It is long enough to overflow from the top and the right of the screen.

### Connect You version

8.1 (27)

### Android version

LineageOS 20

### Other details

Either come up with a shorter temporary chat name (e.g. just the filename, "New contact from .vcf", the contact name within the vcf file), or trim the current chat title in a sensible manner when it's too long, or (preferred) both.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Screenshot?

**Comment by foxyseta** [comment]
![Screenshot_20231213-121931_Connect You](https://github.com/you-apps/ConnectYou/assets/12249077/01acc98a-e93f-45b9-ba20-619594d47523)
The textbox also overflows, but maybe there's another issue about that already?

**Comment by foxyseta** [comment]
Nice!
