### ISSUE TITLE
Add feature to search messages

### ISSUE THREAD

**Issue by thinktankmachine** [you-apps/ConnectYou#352]
### Describe your suggested feature

Please implement a feature to search messages, either within a single chat session with another recipient or multiple recipients, or across all messages. The signal app should be the reference UX layout.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Implemented with https://github.com/you-apps/ConnectYou/commit/9032269fb028e09fd7154efc7eb80cfc09e3528b.
