### ISSUE TITLE
Feature request - Multimedia messaging and recording

### ISSUE THREAD

**Issue by azgaresncf** [you-apps/ConnectYou#357]
### Describe your suggested feature

The proposed feature involves enhancing the current messaging application to support multimedia content sharing. Users would be able to send and receive images and videos, either from their device's gallery or by capturing new ones using the in-app camera, as it is not included in the current version of the application. Additionally, the feature includes the ability to record and send voice messages within the application.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
As already stated out, that's not planned from our side.

**Comment by M00NJ** [comment]
I'll add a section to the readme with an explanation to why we won't work on this, if that's cool with you.

**Comment by azgaresncf** [comment]
Sorry if I have distrubed you.

**Comment by M00NJ** [comment]
> Sorry if I have distrubed you.

No worries. We just get this a lot and have explaned many times why we won't work on this. I will pin an explanation somewhere so it's more visible.

**Comment by M00NJ** [comment]
@Bnyro what would you prefer, pinning and issue with our reasoning or adding a section to the readme?

**Comment by Bnyro** [comment]
> @Bnyro what would you prefer, pinning and issue with our reasoning or adding a section to the readme?
>
I'd prefer the Readme, but I doubt many people read it till the end. It's up to you.
