### ISSUE TITLE
Add formatting for phone numbers

### ISSUE THREAD

**Issue by user8446** [you-apps/ConnectYou#358]
### Describe your suggested feature

Hi, 

It would be great if phone numbers automatically added formatting like the stock contacts app. 

Currently in Connect You: 

2024567890 

Suggested: 

(202) 456-7890 
or 
202-456-7890

Thank You

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In German, numbers are usually formatted with spaces only, like `0123 4567 8910`. I don't think we will find a number format that is intuitive for users with different locales.

**Comment by user8446** [comment]
Hi would it be an easy solution with something like this?

PseudoCode:

if locale = United States then format = xxx-xxx-xxxx

elseif locale = Germal then format = xxx xxxx xxxx

**Comment by Bnyro** [comment]
Well, by that we have 2 out of 200 possible locales covered 🙈

**Comment by user8446** [comment]
Your right, makes sense!

I'm not sure how stock Google Contacts does it since we can't see the code.

**Comment by o0nd7ots** [comment]
I think that the option to add spaces is enough, at least for now.

I am sure that somwhere there exists a library that would adapt the format for the locales, but I do not know of it.

**Comment by user8446** [comment]
Yes I think spaces would be great as it at least groups the numbers for easier deciphering:

![Screenshot_20240106-123435](https://github.com/you-apps/ConnectYou/assets/18019245/028395dc-0588-4f7e-9353-d8a8c676ac0f)

**Comment by o0nd7ots** [comment]
I am able to add spaces in 8.1 using AnySoftKeyboard.
