### ISSUE TITLE
add keyboard version phone-pad for writing SMS

### ISSUE THREAD

**Issue by keemai** [you-apps/ConnectYou#362]
### Describe your suggested feature

want to use my preferred keyboard version phone-pad with text predictio to write messages
can only write one letter
cursor gets stuck after that

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
As we use the default Jetpack Compose text field without modifications, that's either a keyboard or a compose issue.

**Comment by keemai** [comment]
ok
will keep using Simple SMS which does not have that issue
but thanks for having replied

☮️ Paz Pau Peace Paix Peoc'h Pace Paqja Pax Frieden Vrede Vred Mip Mir мир Miers ειρήνη Barış Aştî Сулҳ Irini Rauha Taika سلام





Feb 14, 2024, 11:31 by ***@***.***:
