### ISSUE TITLE
Please get your app on play store, samsung app store, and mi apps store.

### ISSUE THREAD

**Issue by Varniit-pro-90s** [you-apps/ConnectYou#365]
### Describe your suggested feature

Please get your app on play store, samsung app store, and mi apps store.

App not present on any stores. It will help others know and use this app better as compared to default spyware google messages.

It is a humble request as a month long user. 

Loved your app and dont want it to live in obscurity. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No.

**Comment by Bnyro** [comment]
We will not publish any apps to non-foss services.

**Comment by Varniit-pro-90s** [comment]
> We will not publish any apps to non-foss services.

I was just giving suggestions for more users since nobody knows about your apps but to each his own.
