### ISSUE TITLE
Ability to translate fastlane/metadata/android files

### ISSUE THREAD

**Issue by Artem13327** [you-apps/ConnectYou#368]
### Describe your suggested feature

Translation of the application is available on Weblate, why not give the opportunity to translate fastlane/metadata/android files

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You're free to do so via a pull request - we don't plan to add it to Weblate because the app translation itself is way more important and we rather want contributors to focus on that than the metadata translation.
