### ISSUE TITLE
ConnectYou 9.0 F-droid trips PlayProtect

### ISSUE THREAD

**Issue by m0yP** [you-apps/ConnectYou#370]
### Steps to reproduce

Updated to version 9.0 from F-droid and got the screen from Play Protect regarding this as a harmful app.

### Expected behavior

Should not show this warning

### Actual behavior

![Screenshot_20240207-072612](https://github.com/you-apps/ConnectYou/assets/22119314/3a6966a7-1cc1-40ae-9624-cff7e7e975bd)

### Connect You version

9.0

### Android version

Android 14

### Other details

Just the error message. App runs ok.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Play Protect is not relevant for the project, it's usually showing warning for any apps that are not installed via Play Store.
