### ISSUE TITLE
Switch between landscape and portrait resets the tab we're at and bring back to the start tab

### ISSUE THREAD

**Issue by Porkepix** [you-apps/ConnectYou#376]
### Steps to reproduce

Be on another tab than the start one, switch between portrait and landscape, see that it brings you back to the start tab

### Expected behavior

It shouldn't change the tab you're on

### Actual behavior

It brings you back at the start tab.

### Connect You version

9.0

### Android version

Android Oreo (8.0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We would need to migrate to [compose navigation](https://developer.android.com/jetpack/compose/navigation) instead of using full screen dialogs to fix that, contributions welcome.

**Comment by Bnyro** [comment]
Sure, just create a PR when you're done :+1:
