### ISSUE TITLE
SMS deletion not possible

### ISSUE THREAD

**Issue by hanebuch** [you-apps/ConnectYou#378]
### Steps to reproduce

SMS deletion does not work after "OK" confirmation

### Expected behavior

After the "OK" confirmation, the SMS should disappear, but it does not

### Actual behavior

SMS deletion does not work after "OK" confirmation

### Connect You version

9.0

### Android version

Android 14

### Other details

Samsung Galaxy A52  One UI 6.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You have to make Connect You the default SMS app in Android Settings first.
