### ISSUE TITLE
App drops field values when adding through intent compared to that of importing vcf

### ISSUE THREAD

**Issue by N1N74** [you-apps/ConnectYou#383]
### Steps to reproduce

Essentially a bug report on findings [here](https://gitlab.com/Atharok/BarcodeScanner/-/issues/63):
1. Have an app (like for eg. Barcode scanner) send intent to ConnectYou with fields such as secondary number, website, job title, etc.
2. Connect you drops some fields entirely (secondary number, website, job title are dropped)
3. Use another app for the intent to confirm that other apps can recognize the secondary number perfectly fine (not fossify contacts, also has same issue. Samsung default contacts worked.) 
4. Save the vcard as a vcf and open in ConnectYou
5. This time, all the fields are imported semi-faithfully (secondary number recognized, address becomes single line, no other change)

### Expected behavior

Recognize secondary number through the provided intent

### Actual behavior

The example fields are dropped.

### Connect You version

6.0

### Android version

14

### Other details

Copy pasting example intent that was originally passed via barcode scanner, (see [barcode scanner issue](https://gitlab.com/Atharok/BarcodeScanner/-/issues/63)), to ConnectYou using [app manager](https://f-droid.org/en/packages/io.github.muntashirakon.AppManager/)'s interceptor:

```
URI	intent:#Intent;action=android.intent.action.INSERT;type=vnd.android.cursor.dir/raw_contact;launchFlags=0x3000000;S.secondary_phone=%2B1%20672%20326%2065;S.phone_type=WORK;S.postal=4855%2C%20lonely%20Oak%20Drive%0ASpanish%20fort%0AAL%0A36527%0AUSA;S.name=Sara%20Leon;S.email=sara%40gmail.com;S.notes=;S.phone=86346253;S.company=Alena%20ltd;S.email_type=WORK;S.job_title=Co-founder;S.secondary_phone_type=CELL;end

VERSION	1
ACTION	android.intent.action.INSERT
TYPE	vnd.android.cursor.dir/raw_contact
FLAGS	0x3000000
EXTRA	secondary_phone	12	+1 672 326 65
EXTRA	phone_type	12	WORK
EXTRA	postal	12	4855, lonely Oak Drive
Spanish fort
AL
36527
USA
EXTRA	name	12	Sara Leon
EXTRA	email	12	sara@gmail.com
EXTRA	notes	12	
EXTRA	phone	12	86346253
EXTRA	company	12	Alena ltd
EXTRA	email_type	12	WORK
EXTRA	job_title	12	Co-founder
EXTRA	secondary_phone_type	12	CELL
```
QR code which helped barcode scanner send the intent is found on this random [google image](https://cdn03.qrcodechimp.com/qr/PROD/60be06619aaec3072951b013/fm/vcard-qr-code.png). The vcard in question is copy pasted as:
```
BEGIN:VCARD
VERSION:3.0
N:Leon;Sara
FN:Sara Leon
ORG:Alena ltd
TITLE:Co-founder
ADR:;;4855, lonely Oak Drive;Spanish fort;AL;36527;USA
TEL;WORK;VOICE:86346253
TEL;CELL:+1 672 326 65EMAIL;WORK;INTERNET:sara@gmail.com
URL:www.yourwebsite.com
END:VCARD
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. Secondary + tertiary numbers/emails are supported now
2. At this time, Connect You does not support Job titles - hence that field is currently dropped.
3. Android doesn't unfortunately export the `website` at all (as you can see in your app manager data), so there's nothing that could be done about it
