### ISSUE TITLE
please integrate phone into the app 

### ISSUE THREAD

**Issue by Gamer750** [you-apps/ConnectYou#387]
### Describe your suggested feature

Call inside the app itself

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeuroException** [comment]
They are already working on it.
See https://github.com/you-apps/ConnectYou/tree/dialer

**Comment by xusiai** [comment]
> Looks like this is discontinued, any updates on this besides the dialer branch showing 404?

Dialer seem to be in the current branch. However since there hasn't been a release for a long time you'd need to fetch the apk from Github actions.
