### ISSUE TITLE
Please add a floating window for incoming call contacts

### ISSUE THREAD

**Issue by yoyoyoyolol** [you-apps/ConnectYou#388]
### Describe your suggested feature

I hope to add the function of displaying the incoming call contacts in the Android system's floating window when receiving a call. Another open source project "OpenContacts" has this feature, it would be great if ConnectYou has this feature

### Other details

OpenContacts：https://f-droid.org/packages/opencontacts.open.com.opencontacts/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sorry, that's out of scope for the app for now.
