### ISSUE TITLE
Crop feature when adding contact image

### ISSUE THREAD

**Issue by marcelscode** [you-apps/ConnectYou#390]
### Describe your suggested feature

When adding an image for an contact, give the option to crop the image. Only store the cropped part in the contacts entry.
Typically, I only want the face of a person taken from a full-body shot. At the moment, the whole image is taken as contact image.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please edit the photo with an external image editor before, that's out of scope for the app.
