### ISSUE TITLE
Automatic birthday reminder

### ISSUE THREAD

**Issue by apprehensions** [you-apps/ConnectYou#395]
### Describe your suggested feature

Check if anyone's birthday date in the contacts list is today, and send a notification.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Out of scope, there are other apps for birthday reminders.

**Comment by apprehensions** [comment]
Shame, would have loved to have it built-in so i don't install more bloat.

Any suggestions atleast?
