### ISSUE TITLE
Private SMS Database

### ISSUE THREAD

**Issue by KhalidDuel** [you-apps/ConnectYou#403]
### Steps to reproduce

1. Click the three dots in the top right corner.
2. Click settings
3. In the "Messages" tab, enable "Private SMS Database"
4. Send a message to anyone.

### Expected behavior

The contents of the message should show.

### Actual behavior

A small empty box appears where the should be text.

### Connect You version

9.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce on the latest debug version, thus assuming it's fixed there.
