### ISSUE TITLE
Export and import SMS

### ISSUE THREAD

**Issue by DWolf-19** [you-apps/ConnectYou#405]
### Describe your suggested feature

Add feature for exporting all SMS messages to a file and importing them to the app.

### Other details

It's already implemented in the [Fossify Messages](https://github.com/FossifyOrg/Messages). Old correspondence may remain in SMS messages, as well as some sort of banking transaction log. It would be useful to have a feature of transferring messages when changing device.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Connect You doesn't support MMS, and I fail to see a reason to implement this for SMS.

Please properly update the issue template with more information.

**Comment by DWolf-19** [comment]
Edited, btw.
