### ISSUE TITLE
Importing vCards drops part of names

### ISSUE THREAD

**Issue by Michmcb** [you-apps/ConnectYou#408]
### Steps to reproduce

When importing a .vcf file, in some cases part of the name will be dropped. I've attached an example. This happens with people as well, not just organizations.
`import.vcf` is the file that is being imported. `result.vcf` is the exported result. Part of the name has been lost.

[import.vcf.txt](https://github.com/user-attachments/files/16921734/import.vcf.txt)
[result.vcf.txt](https://github.com/user-attachments/files/16921735/result.vcf.txt)

### Expected behavior

When importing, the names should be preserved as is.

### Actual behavior

When importing, the names are modified from what they are in the .vcf which leads to data loss.

### Connect You version

9.0 (28)

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Tested on the latest debug version and it's no longer reproducible.
