### ISSUE TITLE
App resets on orientation change

### ISSUE THREAD

**Issue by nicolarevelant** [you-apps/ConnectYou#409]
### Steps to reproduce

1. Touch second item's bottom bar (SMS)
2. Rotate the device twice

or:

1. Long press on a contact
2. Rotate the device twice

### Expected behavior

App state should be preserved on orientation change

### Actual behavior

App resets

### Connect You version

9.0 (28)

### Android version

14

### Other details

# Possible solution:

app/src/main/java/com/bnyro/contacts/ui/screens/MainAppContent.kt:71 use rememberSaveable instead of remember

app/src/main/java/com/bnyro/contacts/ui/screens/ContactsScreen.kt:74 use rememberSaveable instead of remember

# Screenshots:

<img src="https://github.com/user-attachments/assets/22701e71-6028-442f-8842-75848550e711" width="30%">
<img src="https://github.com/user-attachments/assets/10316183-9573-402b-8085-17c1997d1ee7" width="30%">

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please feel free to directly submit a pull request next time when you already know a possible solution.
