### ISSUE TITLE
🥳 Important Functions For Dial (Multiple  function)

### ISSUE THREAD

**Issue by Notesuree** [you-apps/ConnectYou#420]
### Describe your suggested feature

1. "Add call" ,"change SIM" and "hold call" buttons in call panel (calling)
2. "2-sec pause", "add wait" buttons on the keypad ((in the 3-point option when typing a number)
4. In recent call, swipe right to make a call and left to write a message
5. Total call time
6. Change the background of the call
7. Support for attaching files in messages. Also camera button.
8. Speed dial numbers (FOR KEYPAD)
9. Record a call

### Other details

https://github.com/you-apps/ConnectYou/discussions/418#discussion-7369394

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There are no plans to extend the dialer feature in such a way.
