### ISSUE TITLE
General options for blocking numbers on scale 

### ISSUE THREAD

**Issue by xusiai** [you-apps/ConnectYou#425]
### Describe your suggested feature

Please implement options for blocking numbers on scale e.g.
- Block all unknown numbers
- Block / allow all hidden numbers. 

These need to be separate options because hidden numbers can be related to private services e.g. healthcare and you'd want to be able to allow them whilst still blocking unknown (not in contacts) numbers. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The proposed features are out of scope for the app.
