### ISSUE TITLE
SMS Backup / Manual backup option

### ISSUE THREAD

**Issue by apprehensions** [you-apps/ConnectYou#431]
### Describe your suggested feature

SMS Backup: Allow the ability to backup SMS/MMS messages.
Manual Backup: Currently, the app has settings for making backups, but none to actually export a backup directly on the spot.

### Other details

Call history backup, but it is beyond the scope of this application.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> SMS Backup: Allow the ability to backup SMS/MMS messages.
>
Already implemented in most recent debug builds, see closed issues.

> Manual Backup: Currently, the app has settings for making backups, but none to actually export a backup directly on the spot.
>
Can be done via the three dots menu at the top right.
